# Generated by Django 4.0.3 on 2022-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('klas', models.CharField(max_length=50)),
                ('time_schedule', models.CharField(max_length=50)),
                ('date_started', models.DateField()),
            ],
        ),
    ]
