# Generated by Django 4.0.3 on 2022-06-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
